# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'AppStatsSQLite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppStatsSQLite
  pod 'Moya'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SQLite.swift'

end
